import 'package:dartz/dartz.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../entities/adherence_log_entity.dart';
import '../repositories/adherence_repository.dart';

class LogMedicationTaken
    implements UseCase<AdherenceLogEntity, LogMedicationTakenParams> {
  final AdherenceRepository repository;

  LogMedicationTaken(this.repository);

  @override
  Future<Either<Failure, AdherenceLogEntity>> call(
    LogMedicationTakenParams params,
  ) async {
    final log = AdherenceLogEntity(
      id: '', // Will be generated by repository
      userId: params.userId,
      medicationId: params.medicationId,
      scheduledTime: params.takenAt,
      takenTime: params.takenAt,
      status: AdherenceStatus.taken,
      createdAt: DateTime.now(),
    );

    return await repository.logMedicationTaken(log);
  }
}

class LogMedicationTakenParams {
  final String userId;
  final String medicationId;
  final DateTime takenAt;
  final String? notes;

  LogMedicationTakenParams({
    required this.userId,
    required this.medicationId,
    required this.takenAt,
    this.notes,
  });
}
